import { Request, Response, NextFunction } from "express";

import PDFDocument from "pdfkit";

import { Loan } from "../model/loan.model.js";

/**
 * Generate Loan Report PDF
 */
export const generateLoanReport = async (
    req: Request,
    res: Response,
    next: NextFunction
) => {
    try {
        const { loanId } = req.params;

        /**
         * Find Loan
         */
        const loan = await Loan.findById(
            loanId
        ).populate(
            "user",
            "name email"
        );

        if (!loan) {
            return res.status(404).json({
                message: "Loan not found",
            });
        }

        /**
         * Create PDF
         */
        const doc = new PDFDocument({
            margin: 50,
        });

        /**
         * Response Headers
         */
        res.setHeader(
            "Content-Type",
            "application/pdf"
        );

        res.setHeader(
            "Content-Disposition",
            `attachment; filename=loan-report-${loan._id}.pdf`
        );

        /**
         * Pipe PDF
         */
        doc.pipe(res);

        /**
         * Title
         */
        doc
            .fontSize(24)
            .text(
                "Loan Management System",
                {
                    align: "center",
                }
            );

        doc.moveDown();

        doc
            .fontSize(18)
            .text("Loan Report", {
                underline: true,
            });

        doc.moveDown(2);

        /**
         * Loan Details
         */
        doc
            .fontSize(14)
            .text(
                `Loan ID: ${loan._id}`
            );

        doc.text(
            `Customer Name: ${loan.fullName}`
        );

        doc.text(
            `Loan Amount: ₹${loan.amount}`
        );

        doc.text(
            `Interest Amount: ₹${loan.interestAmount}`
        );

        doc.text(
            `Total Repayment: ₹${loan.totalRepayment}`
        );

        doc.text(
            `Status: ${loan.status}`
        );

        doc.text(
            `Purpose: ${loan.purpose}`
        );

        doc.text(
            `Employment Type: ${loan.employmentType}`
        );

        doc.text(
            `Annual Income: ₹${loan.annualIncome}`
        );

        doc.moveDown(2);

        /**
         * Footer
         */
        doc
            .fontSize(12)
            .text(
                "Generated by LMS Pro",
                {
                    align: "center",
                }
            );

        /**
         * Finish
         */
        doc.end();
    } catch (error) {
        next(error);
    }
};